d = {    "fairyocarina" : "fairyocarina",
    "ocarina" : "fairyocarina",
    "ocarina1" : "fairyocarina",
    "ocarina2" : "fairyocarina",
    "strength" : "lift1",
    "strength1" : "lift1",
    "str" : "lift1",
    "s" : "lift1",
    "strength2" : "lift1",
    "strength3" : "lift2",
    "magic" : "magic",
    "m" : "magic",
    "bombs" : "bomb",
    "bomb" : "bomb",
    "b" : "bomb",
    "scale" : "scale1",
    "scale2" : "scale1",
    "sc" : "scale1",
    "goldscale" : "scale1",
    "slingshot" : "slingshot",
    "ss" : "slingshot",
    "boomerang" : "boomerang",
    "bm" : "boomerang",
    "dins" : "din",
    "din" : "din",
    "egg" : "egg",
    "wallet" : "wallet",
    "redtunic" : "redtunic",
    "bluetunic" : "bluetunic",
    "bottle" : "bottle",
    "bot" : "bottle",
    "letter" : "bottle",
    "let" : "bottle",
    "emerald" : "emerald-small",
    "ruby" : "ruby-small",
    "sapphire" : "sapphire-small",
    "em" : "emerald-small",
    "rub" : "ruby-small",
    "saph" : "sapphire-small",
    "hookshot" : "hookshot",
    "longshot" : "hookshot",
    "hs" : "hookshot",
    "ls" : "hookshot",
    "bow" : "bow",
    "firearrow" : "firearrow",
    "lightarrow" : "lightarrow",
    "lights" : "lightarrow",
    "fa" : "firearrow",
    "la" : "lightarrow",
    "boots" : "ironboots",
    "irons" : "ironboots",
    "ib" : "ironboots",
    "hovers" : "hoverboots",
    "hb" : "hoverboots",
    "hoverboots" : "hoverboots",
    "hammer" : "hammer",
    "ham" : "hammer",
    "mirrorshield" : "shield3",
    "ms" : "shield3",
    "mirror" : "shield3",
    "claim" : "claim",
    "" : "",

    "zelda" : "zelda",
    "epona" : "epona",
    "saria" : "saria",
    "zel" : "zelda",
    "epo" : "epona",
    "sar" : "saria",
    "sunsong" : "sunsong",
    "suns" : "sunsong",
    "sun" : "sunsong",
    "songoftime" : "songoftime",
    "songofstorms" : "songofstorms",
    "sot" : "songoftime",
    "storms" : "songofstorms",
    "sos" : "songofstorms",
    "minuet" : "green_note",
    "bolero" : "red_note",
    "serenade" : "blue_note",
    "nocturne" : "purple_note",
    "requiem" : "orange_note",
    "prelude" : "yellow_note",
    "min" : "green_note",
    "bol" : "red_note",
    "ser" : "blue_note",
    "noc" : "purple_note",
    "req" : "orange_note",
    "pre" : "yellow_note",


    "forestmedallion" : "forestmedallion",
    "firemedallion" : "firemedallion",
    "watermedallion" : "watermedallion",
    "shadowmedallion" : "shadowmedallion",
    "spiritmedallion" : "spiritmedallion",
    "lightmedallion" : "lightmedallion",

    "forestm" : "forestmedallion",
    "firem" : "firemedallion",
    "waterm" : "watermedallion",
    "shadowm" : "shadowmedallion",
    "spiritm" : "spiritmedallion",
    "lightm" : "lightmedallion",

    "forestmed" : "forestmedallion",
    "firemed" : "firemedallion",
    "watermed" : "watermedallion",
    "shadowmed" : "shadowmedallion",
    "spiritmed" : "spiritmedallion",
    "lightmed" : "lightmedallion",

    
    "mforest" : "forestmedallion",
    "mfire" : "firemedallion",
    "mwater" : "watermedallion",
    "mshadow" : "shadowmedallion",
    "mspirit" : "spiritmedallion",
    "mlight" : "lightmedallion",

    "mfor" : "forestmedallion",
    "mfir" : "firemedallion",
    "mwat" : "watermedallion",
    "mshad" : "shadowmedallion",
    "mspir" : "spiritmedallion",
    "msha" : "shadowmedallion",
    "mspi" : "spiritmedallion",
    "mlig" : "lightmedallion",
    
    "forestkey" : "forest_key",
    "forkey" : "forest_key",
    "keyforest" : "forest_key",
    "keyfor" : "forest_key",

    "firekey" : "fire_key",
    "firkey" : "fire_key",
    "keyfire" : "fire_key",
    "keyfir" : "fire_key",
    
    "waterkey" : "water_key",
    "watkey" : "water_key",
    "keywater" : "water_key",
    "keywat" : "water_key",
    
    "shadowkey" : "shadow_key",
    "shadkey" : "shadow_key",
    "keyshadow" : "shadow_key",
    "keyshad" : "shadow_key",
    
    "spiritkey" : "spirit_key",
    "spirkey" : "spirit_key",
    "keyspirit" : "spirit_key",
    "keyspir" : "spirit_key",
    
    "ganonkey" : "ganon_key",
    "gankey" : "ganon_key",
    "keyganon" : "ganon_key",
    "keygan" : "ganon_key",
    
    "botwkey" : "botw_key",
    "wellkey" : "botw_key",
    "keybotw" : "botw_key",
    "keywell" : "botw_key",
    
    "fortresskey" : "fortress_key",
    "fortkey" : "fortress_key",
    "keyfortress" : "fortress_key",
    "keyfort" : "fortress_key",
    
    "gtgkey" : "gtg_key",
    "keygtg" : "gtg_key",



    
    "bkeyforest" : "forest_bkey",
    "bkeyfire" : "fire_bkey",
    "bkeywater" : "water_bkey",
    "bkeyshadow" : "shadow_bkey",
    "bkeyspirit" : "spirit_bkey",
    "bkeyganon" : "ganon_bkey",
    
    
    "bosskeyforest" : "forest_bkey",
    "bosskeyfire" : "fire_bkey",
    "bosskeywater" : "water_bkey",
    "bosskeyshadow" : "shadow_bkey",
    "bosskeyspirit" : "spirit_bkey",
    "bosskeyganon" : "ganon_bkey",
    "bosskeyganons" : "ganon_bkey",

    "bkeyfor" : "forest_bkey",
    "bkeyfir" : "fire_bkey",
    "bkeywat" : "water_bkey",
    "bkeyshad" : "shadow_bkey",
    "bkeyspir" : "spirit_bkey",
    "bkeygan" : "ganon_bkey",
    "bkeygan" : "ganon_bkey",

    "forestbkey" : "forest_bkey",
    "firebkey" : "fire_bkey",
    "waterbkey" : "water_bkey",
    "shadowbkey" : "shadow_bkey",
    "spiritbkey" : "spirit_bkey",
    "ganonbkey" : "ganon_bkey",
    "ganonsbkey" : "ganon_bkey",


    "forestbosskey" : "forest_bkey",
    "firebosskey" : "fire_bkey",
    "waterbosskey" : "water_bkey",
    "shadowbosskey" : "shadow_bkey",
    "spiritbosskey" : "spirit_bkey",
    "ganonbosskey" : "ganon_bkey",
    "ganonsbosskey" : "ganon_bkey",


    "forbkey" : "forest_bkey",
    "firbkey" : "fire_bkey",
    "watbkey" : "water_bkey",
    "shadbkey" : "shadow_bkey",
    "spirbkey" : "spirit_bkey",
    "ganbkey" : "ganon_bkey",}


d2 = {
    "lift1" : "Progressive Strength",
    "lift2" : "Progressive Strength",
    "lift3" : "Progressive Strength",
    "fairyocarina" : "Ocarina Upgrade",
    "ocarina" : "Ocarina of Time",
    "magic" : "Magic",
    "bomb" : "Bombs",
    "scale1" : "Progressive Scale",
    "scale2" : "Progressive Scale",
    "slingshot" : "Slingshot",
    "boomerang" : "Boomerang",
    "din" : "Din's Fire",
    "egg" : "Weird Egg",
    "redtunic" : "Red Tunic",
    "bluetunic" : "Blue Tunic",
    "wallet" : "Adult's Wallet",
    "bottle" : "Bottle",
    "letter" : "Letter",
    "emerald-small" : "Kokiri Emerald",
    "ruby-small" : "Goron Ruby",
    "sapphire-small" : "Zora's Sapphire",
    "hookshot" : "Progressive Hookshot",
    "longshot" : "Progressive Hookshot",
    "bow" : "Bow",
    "firearrow" : "Fire Arrows",
    "lightarrow" : "Light Arrows",
    "ironboots" : "Iron Boots",
    "hoverboots" : "Hover Boots",
    "hammer" : "Hammer",
    "shield3" : "Mirror Shield",
    "claim" : "Claim Check",
    "zelda" : "Zelda's Lullaby",
    "epona" : "Epona's Song",
    "saria" : "Saria's Song",
    "sunsong" : "Sun's Song",
    "songoftime" : "Song of Time",
    "songofstorms" : "Song of Storms",
    "green_note" : "Minuet of Forest",
    "red_note" : "Bolero of Fire",
    "blue_note" : "Serenade of Water",
    "purple_note" : "Nocturne of Shadow",
    "orange_note" : "Requiem of Spirit",
    "yellow_note" : "Prelude of Light",

    "forestmedallion" : "Forest Medallion",
    "firemedallion" : "Fire Medallion",
    "watermedallion" : "Water Medallion",
    "shadowmedallion" : "Shadow Medallion",
    "spiritmedallion" : "Spirit Medallion",
    "lightmedallion" : "Light Medallion",

    "forest_key" : "Forest Key",
    "fire_key" : "Fire Key",
    "water_key" : "Water Key",
    "shadow_key" : "Shadow Key",
    "spirit_key" : "Spirit Key",
    "ganon_key" : "Ganon's Key",
    "botw_key" : "BOTW Key",
    "fortress_key" : "Fortress Key",
    "gtg_key" : "GTG Key",

    "forest_bkey" : "Forest Boss Key",
    "fire_bkey" : "Fire Boss Key",
    "water_bkey" : "Water Boss Key",
    "shadow_bkey" : "Shadow Boss Key",
    "spirit_bkey" : "Spirit Boss Key",
    "ganon_bkey" : "Ganon Boss Key",


    
}

for k, v in d.items():
    try:
        print("%s %s  " % ("{:20}".format("%s:" % k), d2[v]))
    except:
        pass

print("\n\n")




d = {
    'deku' : "Deku Tree",
    'dc' : "Dodongo's Cavern",
    'jabu' : "Jabu Jabu's Belly",
    'botw' : "Bottom of the Well",
    'well' : "Bottom of the Well",
    'dmc' : "D. Mountain Crater",
    'dmt' : "D. Mountain Trail",
    'desert' : "Desert Colossus",
    'colossus' : "Desert Colossus",
    'fire' : "Fire Temple",
    'forest' : "Forest Temple",
    'ganonout' : "Ganon's Exterior",
    'ganon' : "Ganon's Castle",
    'ganons' : "Ganon's Castle",
    'ganontower' : "Ganon's Tower",
    'fortress' : "Gerudo Fortress",
    'gtg' : "G. Training Grounds",
    'goron' : "Goron City",
    'graveyard' : "Graveyard",
    'wasteland' : "Haunted Wasteland",
    'castle' : "Hyrule Castle",
    'field' : "Hyrule Field",
    'market' : "Hyrule Market",
    'ice' : "Ice Cavern",
    'icecavern' : "Ice Cavern",
    'kak' : "Kakariko Village",
    'kokiri' : "Kokiri Forest",
    'hylia' : "Lake Hylia",
    'lake' : "Lake Hylia",
    'ranch' : "Lon Lon Ranch",
    'lw' : "Lost Woods",
    'lostwoods' : "Lost Woods",
    'meadow' : "S. Forest Meadow",
    'sfm' : "S. Forest Meadow",
    'shadow' : "Shadow Temple",
    'spirit' : "Spirit Temple",
    'temple' : "Temple of Time",
    'water' : "Water Temple",
    'domain' : "Zora's Domain",
    'fountain' : "Zora's Fountain",
    'river' : "Zora's River",}


for k, v in d.items():
    try:
        print("%s %s  " % ("{:20}".format("%s:" % k), v))
    except:
        pass

print("\n\n")